/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import BD.GestionBD;
import Utilidades.Imagenes;
import insertar.InsertarCancion;
import insertar.InsertarDisco;
import insertar.InsertarInterprete;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hector Pose Carames
 */
public class Principal extends javax.swing.JFrame {

    GestionBD ges = new GestionBD();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taboa1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taboa2 = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnMostrarD = new javax.swing.JButton();
        btnInsetar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnInsertar2 = new javax.swing.JButton();
        btnMostrarC = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taboa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Genero", "Imagen"
            }
        ));
        taboa1.setRowHeight(40);
        jScrollPane1.setViewportView(taboa1);

        taboa2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "ID", "Titulo", "Imagen"
            }
        ));
        taboa2.setRowHeight(40);
        jScrollPane2.setViewportView(taboa2);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnMostrarD.setText("Mostrar Discos");
        btnMostrarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDActionPerformed(evt);
            }
        });

        btnInsetar.setText("Insertar");
        btnInsetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsetarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnInsertar2.setText("Insertar");
        btnInsertar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar2ActionPerformed(evt);
            }
        });

        btnMostrarC.setText("Mostrar Canciones");
        btnMostrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCActionPerformed(evt);
            }
        });

        jButton2.setText("InsertarC");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInsetar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInsertar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsetar)
                    .addComponent(btnActualizar)
                    .addComponent(btnInsertar2)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnMostrarD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(btnSalir))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInsetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsetarActionPerformed
        InsertarInterprete ins = new InsertarInterprete();
        ins.setVisible(true);        
    }//GEN-LAST:event_btnInsetarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        taboa1.setDefaultRenderer(Object.class, new Imagenes());
        String[]nombreColumnas={"ID","Nombre","Genero","Imagen"};
        DefaultTableModel ta = (DefaultTableModel) taboa1.getModel();
        ta = new DefaultTableModel(ges.tablaI(),nombreColumnas){
            @Override
            public Class getColumnClass(int column)
            {
//                if (column==nombreColumnas.length-1){
//                return Icon.class;
//                }
                return getValueAt(0, column).getClass();
            }};
        
        taboa1.setModel(ta);
        taboa1.setPreferredScrollableViewportSize(taboa1.getPreferredSize());
//        ta.setRowCount(0);
//        ArrayList<Object[]> datosTabla = ges.tablaI();
//        for (int i=0;i<datosTabla.size();i++) {
//            Object[]datos=datosTabla.get(i);
//            ta.addRow(datos);
//            taboa1.setValueAt(datos[datos.length-1], i, 3);
            
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnInsertar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar2ActionPerformed
        
        
        int fila = taboa1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un interprete");
        } else {

            
            InsertarDisco ins = new InsertarDisco();
            ins.setVisible(true);
            ins.txtID.setText(taboa1.getValueAt(fila, 0).toString());

        }
    }//GEN-LAST:event_btnInsertar2ActionPerformed

    private void btnMostrarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDActionPerformed
        int fila = taboa1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un interprete");
        } else {
            taboa2.setDefaultRenderer(Object.class, new Imagenes());
        String[]nombreColumnas={"Codigo","ID","Titulo","Imagen"};
        DefaultTableModel ta = (DefaultTableModel) taboa2.getModel();
        ta = new DefaultTableModel(ges.tablaD(taboa1.getValueAt(fila, 0).toString()),nombreColumnas){
            @Override
            public Class getColumnClass(int column)
            {
//                if (column==nombreColumnas.length-1){
//                return Icon.class;
//                }
                return getValueAt(0, column).getClass();
            }};
        
        taboa2.setModel(ta);
        taboa2.setPreferredScrollableViewportSize(taboa2.getPreferredSize());
            }
        
    }//GEN-LAST:event_btnMostrarDActionPerformed

    private void btnMostrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCActionPerformed
        Canciones c = new Canciones();
        c.setVisible(true);
        int fila = taboa2.getSelectedRow();
        if (fila ==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar un disco");
        }else{
            DefaultTableModel ta = (DefaultTableModel) c.taboa3.getModel();
            
            try {
                for (Object[] datos : ges.tablaC(taboa2.getValueAt(fila, 1).toString())) {
                    ta.addRow(datos);
                    
                }  
            } catch (IOException ex) {
                Logger.getLogger(Canciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_btnMostrarCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Principal p = new Principal();
        int fila = taboa2.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un disco");
        } else {

            
            InsertarCancion ins = new InsertarCancion();
            ins.setVisible(true);
            ins.txtCodigo.setText(taboa2.getValueAt(fila, 0).toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnInsertar2;
    private javax.swing.JButton btnInsetar;
    private javax.swing.JButton btnMostrarC;
    private javax.swing.JButton btnMostrarD;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable taboa1;
    public javax.swing.JTable taboa2;
    // End of variables declaration//GEN-END:variables
}
